# Change these first
owner: KyeOnDiscord # Your GitHub organization or username, where this repository lives
repo: Flashcard-Website-Uptime # The name of this repository

sites:
  - name: Flashcards App Website Frontend
    url: https://flashcards.kyedev.xyz
  - name: Flashcards App Website Backend
    url: https://flashcardappbackend.kyedev.xyz
    expectedStatusCodes:
      - 200
      - 404

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status-flashcards.kyedev.xyz
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: Uptime for Flashcard App
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
